// Jaipur · Hriday Mahal vocabulary, v1.0 (Q3 2026).
// Validates against /_shared/vocab.schema.json.
// Loaded as an ES module by /jaipur/index.html and exposed on window.JaipurVocab
// for the Babel-standalone App script that cannot use ES import.
//
// Localization caveat: all Hindi (Devanagari, romaji) here is a Q3 2026 design
// proposal generated by the project authors and awaits review by native Hindi
// speakers (writers, designers, urban planners) before any real-world implementation.
//
// Why Jaipur for the India slot: Jaipur is literally the Pink City. The historic core
// is painted in the Jaipur Pink Limewash, established during the 2006-07 conservation
// of the Hawa Mahal (the Palace of Winds, with its 953 jali windows). The Pink City
// is a literal colour anchor for Cor del Món's rose family, pairing perfectly with
// Marrakech's Red City framing in the Africa cluster. Jaipur is also a planned royal
// city (Sawai Raja Jai Singh II, 1727 to 1731, Vastu Shastra Prastara grid), which
// gives the network a counterpart to Adelaide's Light's grid (1837) and to Yokohama's
// Minato Mirai 21 grid (1988). Three planned-grid cities, 250 years apart, in dialogue.
//
// Real-world context (Q3 2026): UNESCO World Heritage 2019. In November 2025 the World
// Heritage Committee flagged risk to Jaipur's Outstanding Universal Value, asking the
// Rajasthan government for a safeguard report by December 2026. Around 400 historic
// havelis demolished over the years; 122 structures in the heritage zone marked unsafe
// in a 2025 India Today report. The Cor del Món project sites Hriday Mahal OUTSIDE the
// Walled City UNESCO core (proposed Mansarovar or Jhotwara) and offers a heritage-aware
// density alternative through Hriday Ghar housing.

const vocab = {
  city: {
    slug: "jaipur",
    name: { native: "जयपुर", roman: "Jaipur", english: "Jaipur" },
    country: { code: "IN", name: "India" },
    coords: { lat: 26.9124, lon: 75.7873, tz: "Asia/Kolkata" },
    locale: "hi-IN",
    hreflang: "hi"
  },
  brand: {
    monument:  { native: "हृदय महल",   roman: "Hriday Mahal",   english: "Heart Palace" },
    home:      { native: "हृदय घर",     roman: "Hriday Ghar",    english: "Hearts of Home" },
    network:   { native: "हृदय जाल",   roman: "Hriday Jaal",    english: "Heart Network" },
    residency: { native: "हृदय निवास",  roman: "Hriday Niwas",   english: "Heart Residency" },
    tagline:   { native: "गुलाबी शहर का हृदय", roman: "Gulabi shahar ka hriday", english: "Heart of the Pink City" }
  },
  palette: {
    "--rose":         "#e91e63",
    "--rose-dark":    "#880e4f",
    "--rose-light":   "#f48fb1",
    "--rose-pale":    "#fce4ec",
    "--bg":           "#0f0612",
    "--text-primary": "#fae0eb",
    "--text-muted":   "#b48aa3",
    "--accent":       "#ad1457"
  },
  typography: {
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Noto+Serif+Devanagari:wght@400;700;900&family=Inter:wght@300;400;500;600;700&display=swap",
    serif: "'Noto Serif Devanagari', Georgia, serif",
    sans:  "'Inter', system-ui, -apple-system, sans-serif"
  },
  monument: {
    heightM: 12,
    name: "Hriday Mahal",
    completionYear: 2040,
    signature: "A 12 metre Heart Palace in Mansarovar, southwest of the Walled City and outside the UNESCO heritage buffer, the same 12 metre heart every Cor city builds. Kept low and pink, in the scale of the old city, roughly the height of the Hawa Mahal itself. Pink-limewashed sandstone facade in the same Jaipur Pink that defined the historic core in 1876, when Maharaja Sawai Ram Singh painted the city for the Prince of Wales's visit. Jali screens in the Hawa Mahal tradition, 953 of them as a homage to the Palace of Winds, set in lime plaster and re-limewashed each monsoon the way the city has always kept its colour, the sacrificial coat that lets the sandstone last a century. Marble plinth from Makrana. By night, during accepted hours, the little pink heart blooms into a far larger heart of light that beats in time with all six cities, weightless and fully reversible, dimmed toward the Walled City and protected views. A second heart, beating outside the Walled City so the Walled City can keep beating its own, identical at its core to its five sisters around one flame."
  },
  nationalStyle: {
    materials: [
      { name: "Jaipur Pink Limewash",     sourceRegion: "Established 2006-07 during Hawa Mahal conservation, sampled from the 1876 original",  role: "Facade colour across every panel; the city's identity-defining hue made a precise specification" },
      { name: "Bharatpur red sandstone",  sourceRegion: "Bharatpur quarries, Rajasthan",                              role: "Plinth, jharokha balcony brackets, jali screen frames" },
      { name: "Makrana white marble",     sourceRegion: "Makrana quarries (the Taj Mahal source), Rajasthan",         role: "Floor inlay, ceremony pavilion bench, eternal flame surround" },
      { name: "Brass and copper inlay",   sourceRegion: "Jaipur metalwork tradition (Sanganer and Bagru workshops)",  role: "Door pulls, jali centre medallions, ceremony bowl rims" },
      { name: "Lac and gemstone inlay",   sourceRegion: "Jaipur gem-cutting and lac-craft tradition",                  role: "Decorative inlay around the eternal flame, mirroring traditional Rajasthani jharokha" }
    ],
    motifs: [
      { name: "Jali lattice (953)",       origin: "Hawa Mahal's 953 jali windows (1799, Maharaja Sawai Pratap Singh)", application: "Hriday Mahal carries the same number, 953 jali openings across the eight floors and the entry pavilion. A direct architectural homage." },
      { name: "Chhatri pavilion",         origin: "Rajasthani chhatri (umbrella-shaped roof element) tradition",       application: "Eight rooftop chhatris, one per ceremony floor, in the City Palace lineage" },
      { name: "Jharokha balcony",         origin: "Rajasthani oriel-window tradition, prominent at Hawa Mahal and Amer Fort", application: "Eastern facade carries a series of jharokha balconies for couples-ceremony use" },
      { name: "Vastu Shastra Prastara",   origin: "Sawai Raja Jai Singh II's 1727 city plan, derived from the Prastara variant of Vastu Shastra", application: "Floor plan logic of the building: nine squares (chowks) in a grid, with the central chowk holding the eternal flame, mirroring the city's own original plan" },
      { name: "Pink Limewash uniformity", origin: "1876 painting of the Walled City for the Prince of Wales's visit",  application: "The facade is a single pink, no decorative variation, as a deliberate echo of the Walled City's own uniformity rule" }
    ],
    buildingTypology: "Pink-limewashed sandstone facade with 953 jali openings, on a Bharatpur red-sandstone plinth, with eight rooftop chhatris and a Vastu Shastra Prastara grid floor plan",
    referenceArchitects: ["Charles Correa (Jawahar Kala Kendra, Jaipur, 1992)", "Sanjay Puri (Sanjay Puri Architects, Mumbai)", "Anupama Kundoo (Auroville, sustainable materials)", "Bijoy Jain (Studio Mumbai, craft-based traditional materials)"],
    silhouette: "A pink-limewashed heart with eight chhatri pavilions on the roof, jali-screened on every elevation, marble-plinthed at the base, sited outside the Walled City to honour the UNESCO buffer"
  },
  seismic: {
    code: "IS 1893 (Part 1):2016 Indian Standard for Earthquake-Resistant Design, Zone II for Jaipur (low seismic activity); IS 456 for reinforced concrete; IS 13920 for ductile detailing",
    designSpec: "Jaipur sits in IS 1893 Zone II, the lowest seismic-hazard zone in India. The Aravalli stable craton beneath Jaipur has been geologically quiet for hundreds of millions of years. Hazard factor (Z) is 0.10g.",
    peakAccel: "0.10g design / 0.18g MCE",
    isolation: "No base isolation needed at this seismicity level. Reinforced concrete core with internal vertical steel and post-tensioning in the Bharatpur sandstone plinth. The 953 jali openings are detailed for in-plane shear with stainless steel ties at every fourth course.",
    notes: "Jaipur's seismic context is the gentlest in the network (lower than Andorra, much lower than Tokyo or Yokohama). The structural challenge is not earthquake but the long thermal cycle: 4°C winter mornings to 45°C summer afternoons demand serious thermal-expansion detailing in the marble plinth and the jali screens.",
    designConsequences: "Without base isolation cost, the budget shifts to materials craft (the 953 jali screens are hand-cut by Sanganer and Karauli stonemasons, taking three years), to the gemstone and lac inlay around the eternal flame, and to the Pink Limewash recipe (sampled and conserved exactly to the 1876 original)."
  },
  sections: {
    hero: {
      label: "गुलाबी शहर",
      title: "Jaipur,",
      titleAccent: "गुलाबी शहर का हृदय",
      lead: "Greater Jaipur, around 4.41 million people on the Aravalli plateau. The Pink City: planned in 1727 by Sawai Raja Jai Singh II in a single phase using a Vastu Shastra Prastara grid, painted pink in 1876 for the Prince of Wales's visit, and that pink is now the colour of every facade in the Walled City. UNESCO World Heritage 2019. Hawa Mahal's 953 jali windows are the architectural signature. In November 2025, UNESCO flagged risk to the Walled City's Outstanding Universal Value (around 400 historic havelis lost over the decades, 122 structures unsafe in 2025). Cor del Món asks Jaipur to do what Sawai Raja Jai Singh II did in 1727: plan a heart-shaped block from scratch, in the right place, with the right materials, at the right time.",
      viral: "The city that the world copied for its colour can teach the world how to keep loving it.",
      stats: [
        { n: "12m",      l: "Hriday Mahal (the shared heart, +heartbeat of light)" },
        { n: "953",      l: "Jali openings (Hawa Mahal homage)" },
        { n: "800",      l: "Hriday Ghar + 14 havelis by 2040" },
        { n: "1 hr/wk",  l: "Jaipur Hour on Cor FM" },
        { n: "Q1 2034",  l: "First Families Move In" }
      ]
    },
    monumentSection: {
      label: "हृदय महल",
      title: "Hriday Mahal",
      lead: "The Heart Palace. 12 metres of pink-limewashed sandstone with 953 jali openings (one for every Hawa Mahal window, the Palace of Winds itself about this height), a Vastu Shastra Prastara nine-chowk floor plan with the eternal flame at the central chowk. Kept low and pink in Mansarovar, outside the Walled City UNESCO buffer. By night it blooms into a far larger heart of light beating with all six cities, dimmed toward the Walled City.",
      viral: "Not a tower in the Pink City skyline. A second heart, beating outside the Walled City so the Walled City can keep beating its own."
    },
    passivhaus: {
      label: "हृदय घर",
      title: "Hriday Ghar",
      subtitle: "Heritage-aware family homes for the Pink City",
      lead: "Jaipur grows at 2.37% per year and Rajasthan's Mukhyamantri Awas Yojana already builds around 20,000 affordable homes a year. The binding constraint is heritage loss (around 400 historic havelis demolished, 122 unsafe per India Today 2025; UNESCO flagged the Walled City's Outstanding Universal Value at risk in November 2025), not new-build supply. The Cor del Món contribution is two-track: 800 new Hriday Ghar family homes by 2040 (400 Mansarovar + 250 Jhotwara + 150 Vidhyadhar Nagar; pink-limewashed sandstone courtyard houses with deep jali screens for passive cooling through the 45°C summer), and 14 Walled City havelis brought back to occupancy through the Hriday Niwas residency rotation. The havelis are the headline; the new-build is the secondary.",
      viral: "A house that looks like a haveli, breathes like a haveli, and was built in 2034 for a family that wants to stay in Jaipur",
      cards: [
        { icon: "leaf",   title: "Jali-cooled, deep-veranda design",    desc: "953 jali openings per block (the Hawa Mahal homage scaled for housing). Deep verandahs on the south and west. Cross-ventilation through a heart-shaped courtyard. Pink Limewash reflects the summer sun. Energy use roughly 70% below a conventional Jaipur apartment." },
          { icon: "heart",  title: "Pink-courtyard haveli blocks",         desc: "Each block of 12 units around a heart-shaped courtyard with a stepwell-inspired water feature, a single neem tree, and a jharokha balcony for every unit. Communal under-verandah kitchen, shared bath house, rooftop drying court." },
        { icon: "hearth", title: "Family-first, three-generation",      desc: "Every unit: 3+ bedrooms, soundproofed nurseries, an alcove for an elder family member (essential for Indian multi-generational households), sliding panels reconfiguring the floor plan as the family grows." },
        { icon: "key",    title: "Subsidised for young families",       desc: "Eligible Jaipur residents under 35 with two-plus years of residency: up to 30% subsidy on Hriday Ghar units, scaled by number of children. Income-tested. Coordinated with the Government of Rajasthan's Mukhyamantri Awas Yojana housing programme. Proposed Q3 2026." },
        { icon: "sun",    title: "Net-zero, solar-shaded jali",         desc: "Solar shingles on the chhatri-roofed pavilion, geothermal warmth from the Aravalli aquifer, rainwater harvesting through stepwell-inspired courtyard cisterns. Bills minimal year round, even through the 45°C peak." },
        { icon: "arc",    title: "Timeline: Q1 2034 start",             desc: "Phase 1 (2034-2036): 400 units in Mansarovar. Phase 2 (2036-2038): 250 in Jhotwara (industrial-zone conversion). Phase 3 (2038-2040): 150 in Vidhyadhar Nagar (transit-oriented infill near the Jaipur Metro). Total 800. In parallel: the first 8 of 14 Walled City havelis brought back to occupancy through the Hriday Niwas residency rotation. All builds reviewed under IS 1893 Zone II for the Jaipur intra-plate seismic context." }
      ],
      stats: [
        { n: "800",   l: "Homes by 2040 (+ 14 havelis restored)" },
        { n: "70%",   l: "Energy below baseline" },
        { n: "Up to 30%", l: "Family Subsidy" },
        { n: "3+",    l: "Bedrooms Min" }
      ]
    },
    architecture: {
      label: "प्रेम की वास्तुकला",
      title: "Buildings That Stay Pink",
      lead: "Heart-shaped buildings in Pink Limewashed sandstone with jali screens. Existing concrete walls along Tonk Road and MI Road wrapped in laser-cut jali panels, lit from within during the Cor Biennale 2037. The Pink City extending beyond the Walled City, on its own terms.",
      viral: "Other cities have a colour. Jaipur is a colour, and now the Pink City builds a second heart that keeps the colour going.",
      murals: [
        { text: "ठहरो",         sub: "Thaharo (Stay; LLM-suggested phrasing pending Rajasthani-speaker review). Lac-inlay jali screen panel on a south-facing Mansarovar wall, the 953-jali Hawa Mahal homage rendered as a residential mural.",         gradient: "linear-gradient(135deg,#e91e63,#880e4f)" },
        { text: "गुलाबी में",     sub: "Gulabi mein (In Pink). Pink Limewash brushwork in the chhatri-roofed pavilion above Bani Park, repainted every monsoon as the city has done since 1876.",       gradient: "linear-gradient(135deg,#f48fb1,#e91e63)" },
        { text: "जयपुर का दिल",   sub: "Jaipur ka dil (Heart of Jaipur). One Devanagari phrase across a Vidhyadhar Nagar block in jharokha-balcony silhouette, visible from the Jaipur Metro.",  gradient: "linear-gradient(135deg,#fce4ec,#f48fb1)" }
      ]
    },
    media: {
      label: "जयपुर हवा में",
      title: "Jaipur Hour on the network broadcast",
      lead: "Jaipur does not run a separate station. The network broadcast is anchored in Andorra (Cor FM, Cor Play); Jaipur contributes the Jaipur Hour, a weekly Hindi and Rajasthani strand recorded inside Hriday Mahal and carried worldwide via Cor Play from 2040. Locally it works with the broadcasters Rajasthan already has: a kindness segment for children co-produced with Doordarshan Rajasthan and the Jawahar Kala Kendra, and a radio companion with Akashvani (All India Radio) Jaipur, on the air since the 1950s. The Manganiyar and Langa folk musicians of western Rajasthan, showcased in Jaipur, carry the music. The Jaipur Hour is a gift into the network, never a channel over the ones the city loves.",
      viral: "Jaipur did not need a new station. Akashvani has been on the air for seventy years. Jaipur needed an hour the network gives over to Pink.",
      outlets: [
        { icon: "mic", title: "Jaipur Hour · with All India Radio", desc: "A weekly Hindi and Rajasthani hour made with Akashvani (All India Radio) Jaipur and its long folk and children's tradition. Maand folk, sarangi, wedding songs, letters read on air, carried worldwide on Cor Play.", tags: ["Weekly", "Hindi / Rajasthani", "With AIR"] },
        { icon: "screen", title: "Kindness strand · with DD Rajasthan and JKK", desc: "A children's kindness strand co-produced with Doordarshan Rajasthan and the Jawahar Kala Kendra, in the spirit of Sesame Workshop India's Galli Galli Sim Sim. Puppet stories about welcome, the desert word for come-home, and caring for animals.", tags: ["DD Rajasthan", "With JKK", "Children"], tagVariant: "soft" }
      ],
      soundtrackTitle: "गुलाबी शहर का संगीत · The Sound of the Pink City",
      soundtrackIntro: "What it sounds like to walk past the Hawa Mahal at sunset on a winter evening, when the Pink Limewash deepens to ochre. Five pieces from the Maand and folk tradition of Rajasthan, kept by the Manganiyar and Langa musicians and showcased in Jaipur. Click any track to open a YouTube search.",
      soundtrack: [
        { track: "Padharo Mhare Des",       artist: "Maand folk (Manganiyar tradition)", released: 0,    note: "The Rajasthani welcome song: come to my land, stay with us. Sung at Jaipur palace events for a hundred years. Maand is the regional folk mode; the Manganiyar musicians of western Rajasthan are its keepers, and Jaipur is where the rest of the world hears them." },
        { track: "Kesariya Balam",          artist: "Allah Jilai Bai",                   released: 0,    note: "The great song of longing: a woman calling her beloved home across the desert. Allah Jilai Bai, a Padma Shri laureate from Bikaner, is its definitive voice; this is the version Jaipur hears at every wedding." },
        { track: "Gorbandh",                artist: "Rajasthani folk (traditional)",     released: 0,    note: "A folk song about a camel's decorated halter, woven by the women of a household with love and patience. Home, craft, and the working animals that share the desert life, all in one tune." },
        { track: "Raag Bhairavi, sarangi",  artist: "Sultan Khan",                       released: 0,    note: "Bhairavi is the tender morning raag traditionally played to close a concert. Sultan Khan, the late sarangi master of the Sikar lineage near Jaipur, is the instrument's great voice. Not a song with words, but the sound of longing itself." },
        { track: "Nimbooda",                artist: "Rajasthani folk (via Hum Dil De Chuke Sanam, 1999)", released: 1999, note: "A flirtatious Rajasthani folk song carried to the whole country by Bollywood, and still the Pink City wedding-procession default. The folk-to-film bridge, intact and joyful." }
      ]
    },
    traditions: {
      label: "पुनर्कल्पित परंपराएं",
      title: "Three centuries of Pink, hotter fire",
      lead: "Jaipur's traditions already mix Rajasthani, Marwari, Mughal, and Vaishnava cultural threads. The Cor calendar weaves a love thread through every existing festival and adds the Daily Ceremony at the local sunset hour.",
      viral: "Jaipur has been a city of ceremony since 1727. Now it is a city of ceremony inside a network of six.",
      categories: [
        { monogram: "अ", title: "अन्न · Food (the Pink City table)", items: [
          ["Phool-Patta Diwas (फूल-पत्ता दिवस)",   "An annual May day building on the Rajasthani phool-patta (flower-and-leaf) wedding tradition: couples exchange a marigold garland and a paan-leaf book at the Hawa Mahal forecourt. Scheduled to follow the Jaipur Literature Festival each year so visitors are still in town."],
          ["Lassi at the Lassiwala (heart kulhar)", "On the first Sunday of each month, the original Lassiwala on MI Road and three other Bapu Bazaar shops serve Jaipur's famous saffron lassi in heart-stamped clay kulhars. The kulhars are made by the same Sanganer potters who make the everyday ones; the stamp is the only change."],
          ["Daal-baati-churma at Govind Devji",      "A long-table community meal of the Rajasthani staple inside the Govind Devji temple complex (the city's spiritual heart) on the second Saturday of each month. Free for residents, donation for visitors. Profits go to heritage-haveli restoration."],
          ["Ghewar season (Sawan and Teej)",         "The traditional ghewar (disc-shaped sweet) eaten during the Sawan monsoon and at Teej (August) gains a Cor variant: an extra dab of rose syrup and a single saffron strand for couples. Honours the existing seasonal sweet rather than inventing a new one."]
        ]},
        { monogram: "स", title: "संगीत · Music (the Pink City sound)", items: [
          ["Manganiyar at Jawahar Kala Kendra", "Annual love-music evening drawing on the Manganiyar oral tradition of western Rajasthan. Hosted at Jawahar Kala Kendra (Charles Correa's 1991 building) on a single autumn night, line-up curated by the Rupayan Sansthan archive in Jodhpur."],
          ["Hriday Tabla composition",         "A new piece composed each year for tabla and sarod, premiered at the Daily Ceremony at the local sunset hour. Composer rotates through the seven Rajasthani gharana traditions."],
          ["Pink Holi (rangon ka pyaar)",      "The existing Holi festival in Bani Park each March. The Cor addition is a reserved low-intensity rose-pink kund for elders, small children, and anyone who wants the colour without the crush. Honours the festival's existing form."]
        ]},
        { monogram: "उ", title: "उत्सव · Festivals (the Pink City calendar)", items: [
          ["Teej for couples (तीज जोड़ी)", "The existing Teej monsoon festival (a Rajasthani women's tradition) gets a parallel couples' evening on the second Teej night. Open to anyone, anchored at the City Palace forecourt."],
          ["Cor lights at Diwali",          "Diwali week each November adds Cor lighting in Pink Limewash tones across Mansarovar, Jhotwara, and the Walled City facades. The diyas stay on family doorsteps; the rose-tone uplighting is on the public buildings only."],
          ["Yatra to Hawa Mahal (हवा महल यात्रा)", "Annual evening yatra (walking pilgrimage) between Hriday Mahal (Mansarovar) and Hawa Mahal (Walled City), about 8 km. Ends at the original 953 jali windows at sunset. Held on a Saturday in February when the heat is still gentle."]
        ]},
        { monogram: "र", title: "रिवाज़ · Rituals (the human scale)", items: [
          ["Ceremonies at Hriday Mahal",   "Wedding and renewal ceremonies inside the rooftop chhatri pavilion, looking out at the Aravalli foothills. Subsidised for Rajasthan residents, premium for international couples. Scaled for the Western model only; multi-day Hindu weddings stay across their existing baraat venues."],
          ["Hriday Niwas (occupy and steward)", "Jaipur's contribution to the network Cor Residency. Ten incoming residents per year housed in havelis inside the Walled City buffer (Bani Park, C-Scheme) on a twelve-month restoration-and-residency lease. Vacancy drives demolition; occupancy reverses it."],
          ["Hawa Mahal letter wall",       "Handwritten love letters submitted into a small monsoon-shielded pavilion attached to the Hawa Mahal restoration. Exhibited each Holi week; not bound into a book."],
          ["Stepwell of the year",         "Restoration of one historic baori (stepwell) per year by the Hriday Niwas resident cohort. The chosen baori hosts a Cor ceremony at sunset on its first restored evening."]
        ]}
      ]
    },
    youth: {
      label: "युवा रणनीति",
      title: "Save the haveli. House the family. Keep the Pink.",
      lead: "Jaipur grows at 2.37% per year and Rajasthan's TFR is 2.0 (NFHS 2019-2021). Population is not Jaipur's problem; heritage is. Around 400 havelis demolished, 122 unsafe (India Today, 2025). UNESCO flagged the Walled City's Outstanding Universal Value at risk in November 2025. The Cor del Món contribution is heritage-led, not migration-led: heritage-aware Hriday Ghar in Mansarovar, a residency programme that occupies and restores Walled City havelis (the demolitions follow vacancy), and a single MNIT Jaipur studio on jali architecture and Vastu-grounded urbanism. India's Long-Term Visa already exists; what Jaipur needs is people inside the havelis and family housing outside the buffer.",
      viral: "The city that the world copied for its colour does not need a new visa. It needs occupied havelis and a fired Sanganer kiln in every Hriday Ghar courtyard.",
      cards: [
        { icon: "hearth",    tag: "Housing",        title: "Hriday Ghar in Mansarovar (heritage-aware)",         desc: "800 pink-limewashed sandstone family courtyards by 2040 (400 Mansarovar + 250 Jhotwara + 150 Vidhyadhar Nagar; see the Hearth section). The Mukhyamantri Awas Yojana already builds around 20,000 affordable units a year in Rajasthan; the Cor del Món addition is the heritage-aware typology (Pink Limewash, jali geometry, chhatri pavilion) with a young-family priority overlay (under 35, two-plus years Jaipur residency, child-count-scaled subsidy up to 30%) on top of existing quotas." },
        { icon: "residency", tag: "Cor Residency",  title: "Hriday Niwas, Walled City havelis",                  desc: "Jaipur's contribution to the network Cor Residency is structurally different from the other cities: residents do not just live, they occupy and steward. Ten incoming residents per year, each placed in a haveli inside the Walled City buffer (Bani Park, C-Scheme) on a twelve-month restoration-and-residency lease. Vacancy drives demolition; occupancy reverses it." },
        { icon: "book",      tag: "Education",      title: "MNIT Jaipur Jali Studio (one MArch)",                desc: "MNIT Jaipur's School of Architecture and Planning runs a single annual MArch studio focused on jali geometry, Vastu Shastra Prastara grids, and Mediterranean-arid passive cooling for housing. Twenty seats per year including five funded for network-city students. CEPT Ahmedabad and SPA Bhopal external examiners. One studio, well-taught, beats new institutes." },
        { icon: "doublehearts", tag: "Childcare",   title: "Hriday Ghar courtyard creches",                      desc: "Free childcare from 12 months at the courtyard pavilion of every Hriday Ghar block. Built into the haveli-typology so the courtyard is the playground. Coordinated with the Anganwadi network already operating across Rajasthan under ICDS." },
        { icon: "leaf",      tag: "Health",          title: "SMS Hospital postnatal support",                    desc: "SMS Hospital Jaipur (the Sawai Man Singh tertiary public hospital) expands postnatal mental-health support for new parents and couples, funded through the Mukhyamantri Chiranjeevi Swasthya Bima Yojana state insurance scheme. Telehealth across Greater Jaipur for mothers in the outer growth zones." },
        { icon: "transit",   tag: "Movement",        title: "Jaipur Metro Phase 2 Heart spur",                   desc: "A rose-liveried spur off the Jaipur Metro Phase 2 plan (Mansarovar to Badi Chaupar) extending to the Hriday Mahal site. Subsidised for under-25s on weekends. E-bike-share docks at Hriday Ghar blocks linking to Amber Road and Nahargarh weekend walks." },
        { icon: "lock",      tag: "Heritage",        title: "Haveli restoration target (14 by 2040)",            desc: "A parallel commitment that ties Cor del Món to the Walled City: the Hriday Niwas residents restore one haveli per year through the residency rotation. By Operational + 2 (2040), 14 havelis brought back to occupancy. The new monument outside the buffer and the old havelis inside it are one project." },
        { icon: "leaf",      tag: "Animals",         title: "Working animals and street creatures",              desc: "Jaipur lives shoulder to shoulder with its animals: camels, the Amer elephants, street cows, and thousands of community dogs. Cor backs Help in Suffering, the Jaipur animal hospital that has run camel welfare and street-dog sterilisation for decades, supports humane care and retirement for the Amer working elephants, and ties every Hriday Ghar courtyard to a neighbourhood gaushala. Kindness to animals is taught to Pink City children as part of who they are." }
      ],
      stats: [
        { n: "10",     l: "Hriday Niwas haveli residents/yr" },
        { n: "800",    l: "Hriday Ghar by 2040" },
        { n: "20",     l: "MNIT Jali Studio Master of Architecture seats/yr" },
        { n: "14",     l: "Walled City havelis restored by 2040" }
      ]
    },
    network: {
      label: "हृदय जाल",
      title: "Six cities. One heartbeat. One Pink that the world copied.",
      lead: "Jaipur joins Cor del Món as the sixth wave-1 city, completing the network. With Marrakech as the Wave-2 transitional African Red City, the network now has two literal-colour-anchor cities (Jaipur Pink, Marrakech Red) framing the rose family.",
      viral: "Andorra writes love in stone. Yokohama in arrivals. Adelaide in festivals. Valparaíso in colour. Cape Town in water and mountain. Jaipur writes love in Pink Limewash."
    },
    roadmap: {
      label: "लम्बी लहर",
      title: "Four stages, on Jaipur's pace",
      lead: "Hriday Mahal is Jaipur's contribution to Cor del Món. Jaipur joins the network in the Spread phase, opening its monument in 2038-2040 alongside Valparaíso and Cape Town, completing the wave-1 six. Generation arrives in 2063-2065.",
      viral: "Jaipur alone is 953 jali windows in the Pink City. Jaipur inside Cor del Món is the South Asian heart of a six-city network.",
      milestones: [
        {
          year:     2032,
          stage: "Charter",
          commitment: "Cor Charter signed with the Government of Rajasthan and the Jaipur Municipal Corporation. International architecture competition for Hriday Mahal awarded. Site secured in Mansarovar (outside the Walled City UNESCO heritage buffer, honouring the November 2025 UNESCO concern). Heritage-haveli restoration partnership announced as part of the Charter (the new monument and the old havelis are tied together). First Cor Biennale 2037 hosted at Jawahar Kala Kendra ahead of the monument opening.",
          metrics: { charterSigned: true, competitionAwarded: true, siteSecured: "Mansarovar (UNESCO buffer respected)", havelisToRestore: 14 },
          networkContribution: "Jaipur becomes Cor del Món's South Asian anchor. The Pink City colour pairs with Marrakech's Red City framing in the African cluster, giving the network two literal colour-anchor cities. Jaipur's heritage-haveli restoration commitment becomes a model for any future UNESCO-zone Wave-2 city.",
          status: "concept",
          lastVerified: "2026-Q3"
        },
        {
          year:     2034,
          stage: "Break Ground",
          commitment: "Construction begins on Hriday Mahal and on the first 400 Hriday Ghar pink-courtyard units in Mansarovar. The 953 jali screens enter their three-year hand-cutting period at Sanganer and Karauli stonemason workshops. Cor Visa pilot opens with the first 100-couple cohort (proposed Q3 2026). First two havelis in the Walled City buffer enter restoration via the Hriday Niwas residency programme.",
          metrics: { homesUnderConstruction: 400, corVisaCouples: 100, jaliScreensInProduction: 953, havelisInRestoration: 2 },
          networkContribution: "Jaipur publishes the first ten Jaipur-authored Cor Patterns (jali-cooled passive design, Vastu Shastra Prastara nine-chowk floor plan, heritage-aware urban density, pink-limewash facade chemistry). Jaipur is now part of the four-city construction wave alongside Valparaíso, Cape Town, and tail end of Adelaide-Yokohama.",
          status: "concept",
          lastVerified: "2026-Q3"
        },
        {
          year:     2040,
          stage: "Operational",
          commitment: "Hriday Mahal opens. Daily Ceremony begins broadcasting at the local sunset hour from the rooftop chhatri pavilion. The first 650 of 800 Hriday Ghar units delivered: Mansarovar Phase 1 complete (400 done), Jhotwara Phase 2 underway (250 in build), Vidhyadhar Nagar Phase 3 starting (150 to come). The first Cor Generation residents move into the network units. The Hriday Niwas residency partnership with INTACH Rajasthan and the Walled City Heritage Cell has brought the first 4 havelis (in the buffer-adjacent heritage corridor: Bani Park, C-Scheme, Civil Lines, NOT inside the UNESCO core) back to occupancy.",
          metrics: { homes: 1000, monumentHeightM: 12, fertilityRate: 2.0, residentsIncoming: 10, dailyCeremonyActive: true, populationGreaterJaipur: 5500000, havelisRestored: 8 },
          networkContribution: "Jaipur completes the wave-1 six. The Daily Ceremony rotation now spans all six cities. Cor Residency reaches the target 60 incoming per year network-wide. Jaipur-authored patterns reach 30 contributions to the Cor Pattern Library, leading on heritage-aware urban density. The Wave-2 admission process formally opens 2042 with Marrakech (sponsored by Cape Town) as the transitional first-mover.",
          status: "concept",
          lastVerified: "2026-Q3"
        },
        {
          year:     2065,
          stage: "Generation",
          commitment: "Hriday Mahal celebrates twenty-five years operational. The first Cor Generation residents who arrived in 2040 (then in their 20s, now in their 50s) have raised families inside the Hriday Ghar stock. A second-wave expansion adds 400 units across Vaishali Nagar and Bagru, bringing the Cor total to 1,200. The INTACH Rajasthan + Walled City Heritage Cell partnership has brought 9 havelis (about 1 every 3 years; sustainable against the Sanganer/Karauli stoneworker craft cadence) back to occupancy in the buffer-adjacent heritage corridor, with Cor Residency tenants stewarding maintenance. The Pink City's Outstanding Universal Value (UNESCO 2019) is supported through partnership rather than direct intervention; the heritage authorities own the OUV-protection work.",
          metrics: { networkAgeYears: 25, totalHomes: 1200, generationAdults: 800, havelisStewarded: 9 },
          networkContribution: "Jaipur graduates into network elder status alongside Valparaíso and Cape Town. Jaipur mentors Wave-2 South Asian candidate cities (likely Mumbai, Delhi, Ahmedabad, Kolkata, Lahore, Kathmandu, Dhaka). The Pink City Anthology (Letters to Hawa Mahal bound annually) becomes a recognised volume of contemporary Hindi literature.",
          status: "concept",
          lastVerified: "2026-Q3"
        }
      ]
    }
  },
  feasibility: {
    title: "Honest constraints (ईमानदार बाधाएं)",
    intro: "What a 12m heart palace in Mansarovar (deliberately outside the UNESCO Walled City buffer) and an 800-home heritage-aware programme actually have to negotiate with.",
    category: "Mansarovar growth-zone heritage-aware development plus Mukhyamantri Awas Yojana family-priority overlay plus INTACH Rajasthan partnership for buffer-adjacent haveli stewardship. Existing Government of Rajasthan urban-development category. No new permission package required.",
    permissionChain: [
      "Jaipur Development Authority (JDA), site allocation and zoning approval for the Mansarovar parcel. The JDA Commissioner signs.",
      "Jaipur Municipal Corporation Greater (JMC-Greater, also called JGMC; the post-2019 bifurcated municipal body covering Mansarovar, Jhotwara, Vidhyadhar Nagar), building permit. The JMC-Greater Mayor signs the cultural-anchor MoU.",
      "Government of Rajasthan, Department of Urban Development and Housing (UDH), for the Mukhyamantri Jan Awas Yojana (MJAY) family-priority overlay. The Principal Secretary, UDH, signs.",
      "Government of Rajasthan, Department of Art, Literature, Culture and Archaeology (commonly abbreviated DACA), Hriday Mahal cultural-anchor approval.",
      "INTACH Rajasthan plus the Jaipur Walled City Heritage Management Committee (the post-UNESCO 2019 management body convened under JDA), haveli partnership memorandum. The INTACH Convener, Rajasthan Chapter, signs.",
      "Ministry of Home Affairs, Government of India, FCRA registration for the Indian receiving entity (a Section 8 non-profit company holds the construction funds; INTACH Rajasthan holds the heritage-allocated funds).",
      "Ministry of Culture (national), international cultural-partnership recognition under the existing bilateral cultural exchange framework."
    ],
    budgetSources: [
      "Government of Rajasthan, Mukhyamantri Jan Awas Yojana (MJAY) housing capital (existing affordable-housing scheme administered by the Rajasthan Housing Board under UDH).",
      "Government of Rajasthan, Department of Art, Literature, Culture and Archaeology, annual budget allocation.",
      "Ministry of Culture (national), international-partnership line (similar precedent: Aga Khan Trust for Culture's Humayun's Tomb Conservation Project, Delhi, jointly with ASI).",
      "INTACH Rajasthan benefactor consortium, heritage-activity capital.",
      "Cor del Món network partner-share contribution.",
      "Indian philanthropy (Tata Trusts, Aditya Birla Foundation, Infosys Foundation, Bharti Foundation)."
    ],
    items: [
      { area: "Walled City UNESCO core", detail: "Hriday Mahal sits in Mansarovar, southwest of the Walled City and OUTSIDE the UNESCO buffer, by deliberate design. ASI clearance for the monument site is not required because the site is outside the protected zone. The Walled City's Outstanding Universal Value (UNESCO 2019) is preserved by NOT building inside the buffer, not by partnering on it." },
      { area: "Buffer-adjacent havelis", detail: "The Hriday Niwas residency programme operates in the buffer-adjacent heritage corridor (Bani Park, C-Scheme, Civil Lines), NOT inside the UNESCO core. Walled City heritage interventions, where they happen, are led by INTACH Rajasthan and the Walled City Heritage Cell, NOT by Cor del Món. We supply residency tenants who steward; partners do the actual heritage work." },
      { area: "Building permits",        detail: "Mansarovar siting requires Jaipur Development Authority (JDA) and Jaipur Municipal Corporation (JMC) standard approvals only. At 12m, low and pink, it is a small civic building far under any byelaw trigger; the night-time heart of light is an evening projection under standard event-lighting permits, dimmed toward the Walled City. IS 1893 Zone II seismic compliance is trivial at this scale." },
      { area: "Foreign funding",         detail: "All foreign-source contributions registered under India's Foreign Contribution Regulation Act (FCRA). INTACH Rajasthan is the receiving Indian entity for any heritage-allocated funds; Hriday Mahal construction funds flow through a Section 8 (non-profit) Indian company. No FCRA prior-permission shortcuts." },
      { area: "Visa pathway",            detail: "Cor Residency intake (10 per year) operates within India's existing Long-Term Visa and Cultural Activity visa categories. No new visa class proposed. Government of Rajasthan negotiates the dedicated cultural-residency allocation with the Ministry of Home Affairs." },
      { area: "Housing pathway",         detail: "Hriday Ghar new-build sits inside the Government of Rajasthan's Mukhyamantri Awas Yojana programme. Cor del Món adds a heritage-aware typology (Pink Limewash, jali geometry, chhatri pavilion) plus a young-family priority overlay on existing quotas. We do not run a parallel housing programme." },
      { area: "Craft cadence",           detail: "The 953 hand-cut jali screens enter a three-year cutting period at Sanganer and Karauli stonemason workshops. This is not a bottleneck to be optimised; it is the project's cultural heart. The construction timeline (2034 to 2040) is built around the craft cadence, not against it." }
    ]
  },
  costs: {
    title: "Approximate costs (2026 USD)",
    monumentTotal: "USD 3 to 7 million",
    intro: "Order-of-magnitude estimates anchored against comparable Indian heritage-aware civic builds (Charles Correa's Jawahar Kala Kendra cost roughly USD 8M in 1992 rupees adjusted; Sanjay Puri's Mirai House Jaipur cost USD 5M in 2013). Real budgets after international design competition. The lowest network monument cost because the materials are local, the craft is rooted, and the site is outside the UNESCO buffer.",
    stages: [
      { phase: "Charter (2032)",          range: "USD 0.2 to 0.5M",   scope: "International design competition + Government of Rajasthan signing + JDA Mansarovar site allocation + INTACH Rajasthan partnership agreement + FCRA registration" },
      { phase: "Break Ground (2033-34)",  range: "USD 0.5 to 1.2M",   scope: "Marble plinth from Makrana, RC core foundation, IS 1893 Zone II seismic detailing, Sanganer and Karauli stonemason 953-jali commission begins" },
      { phase: "Construction (2034-40)",  range: "USD 1.5 to 3.5M",  scope: "Pink-limewashed Bharatpur sandstone facade, 953 hand-cut jali screens (3-year cutting period), eight rooftop chhatris, Vastu Shastra Prastara nine-chowk floor plan, lac and gemstone inlay around the eternal flame" },
      { phase: "Operational (2040)",      range: "USD 0.8 to 1.8M",   scope: "Jaipur Hour broadcast studio, ceremony chhatri pavilion fitout, opening programme during the Jaipur Literature Festival, partnership integration with Manganiyar oral-tradition archive" }
    ],
    fundingNote: "Funding for the monument leans private: Cor del Món network partner share (35-50%), Indian philanthropy (illustrative: Tata Trusts, Aditya Birla Foundation, INTACH benefactor consortium) (25-35%), small bilateral cultural partnerships (5-10%), and only a modest enabling share from the Government of Rajasthan plus the JDA in-kind site (10-20%). State housing money stays with the Mukhyamantri Awas Yojana homes and INTACH-led haveli stewardship, not the monument. FCRA receiving entity is INTACH Rajasthan for heritage activity, a separate non-profit for monument construction."
  },
  impact: {
    title: "Impact and benefit",
    items: [
      { metric: "800 heritage-aware family homes by 2040",      note: "About 4 weeks of state Mukhyamantri Awas Yojana output over six years; not numerically large. The Cor contribution is the heritage-aware typology (Pink Limewash, jali, chhatri) at residential scale. 400 Mansarovar + 250 Jhotwara + 150 Vidhyadhar Nagar." },
      { metric: "9 Walled City buffer-adjacent havelis stewarded by 2065", note: "Through the Hriday Niwas residency rotation in partnership with INTACH Rajasthan and the Walled City Heritage Cell. About 1 every 3 years; realistic against the Sanganer/Karauli stoneworker craft cadence." },
      { metric: "10 Hriday Niwas residency intake per year",     note: "Each resident lives in a haveli inside the buffer-adjacent corridor on a twelve-month restoration-and-residency lease. Vacancy drives demolition; occupancy reverses it." },
      { metric: "953-jali Hawa Mahal homage at residential scale", note: "The Sanganer and Karauli stonemason workshops are the only craft families in the world who can hand-cut jali at scale. The Hriday Mahal commission keeps that craft network in business for three years and creates demand for similar work afterwards." },
      { metric: "Jaipur Hour on the network broadcast",          note: "Weekly Hindi and Marwari strand from Hriday Mahal studio, going out alongside Akashvani Jaipur, Radio Mirchi, and Doordarshan Rajasthan. Manganiyar oral-tradition contribution to the global Cor FM rotation." },
      { metric: "12m heart + night heart of light, outside the Walled City", note: "The same 12m heart every Cor city builds, outside the UNESCO buffer, in the scale of the old city and roughly the Hawa Mahal's own height. The night-time heart of light beats with all six cities, dimmed toward the Walled City." }
    ]
  },
  alternatives: {
    title: "Lighter expressions of the same idea",
    intro: "The proposal is offered as a creative-research design idea, not as a fundraising plan or a built commitment. The lightest expression below is the recommended default for any city that wishes to honour the idea without a built monument.",
    items: [
      { fallback: "Hologram-only expression (the recommended default)", reason: "The full Cor del Mon city experience delivered as projection, hologram, and augmented-reality installation hosted inside an existing public building, the same night-time heart of light without the 12 metre building beneath it. No new construction, no land take, no seismic or heritage risk, no permits beyond standard public-event approvals. Roughly one to three percent of the built-version cost. Six to eighteen months from agreement to opening night. Fully reversible. The local government keeps complete flexibility to time the installation to its own civic and cultural calendar and to relocate or remove it at any time. The safest and fastest path for any city that wishes to participate without committing to a permanent build." },
      { fallback: "Print, broadcast, and online expression", reason: "The design idea published as a book, an exhibition catalogue, a documentary, an open-access website, and a network of public talks, with no physical installation in the city. Lower cost again, no local-government commitment of any kind required." }
    ]
  }
};

export default vocab;
if (typeof window !== "undefined") {
  window.JaipurVocab = vocab;
}
