// Yokohama · Minatokokoro vocabulary, v1.0 (Q3 2026).
// Validates against /_shared/vocab.schema.json.
// Loaded as an ES module by /yokohama/index.html and exposed on window.YokohamaVocab
// for the Babel-standalone App script that cannot use ES import.
//
// Localization caveat: all Japanese (kanji, kana, romaji) here is a Q3 2026 design
// proposal generated by the project authors and awaits review by native Japanese
// speakers (writers, designers, urban planners) before any real-world implementation.
//
// Why Yokohama for the Japan slot: Yokohama City sits inside Minato Mirai 21, a
// district that routinely permits 200+ metre towers (Landmark Tower 296m). At 12m the
// Minatokokoro is the same small heart every Cor city builds; the bay grandeur comes
// from a reversible night-time heart of light beating with the network, not structure. Yokohama also has the
// strongest sister-city muscle of any Japanese city, with active programmes with
// Vancouver, Lyon, Mumbai, Manila, Shanghai, Odessa, and Constanta.

const vocab = {
  city: {
    slug: "yokohama",
    name: { native: "横浜", roman: "Yokohama", english: "Yokohama" },
    country: { code: "JP", name: "Japan" },
    coords: { lat: 35.4437, lon: 139.6380, tz: "Asia/Tokyo" },
    locale: "ja-JP",
    hreflang: "ja"
  },
  brand: {
    monument:  { native: "港心",        roman: "Minatokokoro",   english: "Port Heart" },
    home:      { native: "心の家",      roman: "Kokoro no Ie",   english: "Hearts of Home" },
    network:   { native: "心の網",      roman: "Kokoro no Ami",  english: "Heart Network" },
    residency: { native: "心宿",        roman: "Kokoro Yado",    english: "Heart Residency" },
    tagline:   { native: "港町の心",    roman: "Minatomachi no Kokoro", english: "Heart of the port city" }
  },
  palette: {
    "--rose":         "#d63384",
    "--rose-dark":    "#7a1c4d",
    "--rose-light":   "#e91e63",
    "--rose-pale":    "#f8b6cf",
    "--bg":           "#0a0612",
    "--text-primary": "#fae0eb",
    "--text-muted":   "#b18497",
    "--accent":       "#ad1457"
  },
  typography: {
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Noto+Serif+JP:wght@400;700;900&family=Inter:wght@300;400;500;600;700&display=swap",
    serif: "'Noto Serif JP', Georgia, serif",
    sans:  "'Inter', system-ui, -apple-system, sans-serif"
  },
  monument: {
    heightM: 12,
    name: "Minatokokoro",
    completionYear: 2036,
    signature: "A 12 metre Port Heart on Pier 8 of Minato Mirai 21, the same 12 metre heart every Cor city builds. Stacked cross-laminated timber under a titanium shingle skin that shrugs off the salt air where ordinary steel would rust, on a small base-isolated frame. Magenta-rose tinted glass, patinated copper, an andesite plinth from the Hakone volcanic field. By night, during accepted hours, the little timber heart blooms into a far larger heart of light over the bay that beats in perfect time with all six cities, doubling in the water at evening, weightless and fully reversible, dimmed where it would touch homes or protected views. Not the tallest thing in MM21 by a wide margin. The most lived-in, and identical at its core to its five sisters around one flame."
  },
  nationalStyle: {
    materials: [
      { name: "Hinoki cypress and sugi cedar", sourceRegion: "Kanagawa and Shizuoka prefecture forests",  role: "Stacked timber pavilions, ceremony floor planks, mass-timber columns above the isolated base" },
      { name: "Titanium shingle cladding",     sourceRegion: "Japanese titanium mills (Kobe Steel lineage)", role: "Bay-facing rainscreen skin, near-inert in salt air where ordinary steel rusts; the proven choice for Japanese coastal landmarks" },
      { name: "Marine-grade (316) stainless",  sourceRegion: "Japanese stainless producers",              role: "Every exposed fixing, anchor, and bearing housing in the splash zone" },
      { name: "Tinted glass curtain wall",     sourceRegion: "AGC plant, Kanagawa",                       role: "Magenta-rose tinted facade catching dawn and evening over the bay" },
      { name: "Patinated copper roofing",      sourceRegion: "Niigata copper",                            role: "Roof shells of the entry pavilion, weathering to deep verdigris green-rose" },
      { name: "Andesite stone",                sourceRegion: "Hakone volcanic field, Kanagawa",           role: "Plinth and ceremony courtyard paving" }
    ],
    motifs: [
      { name: "Lantern silhouette",            origin: "Yokohama bayfront promenade lanterns",            application: "Pavilion crown geometry and night lighting array" },
      { name: "Boat hull curves",              origin: "Port heritage, NYK Hikawa Maru, working harbour", application: "Curve of the eastern bay-facing facade" },
      { name: "Yamate brick coursing",         origin: "Western quarter (Yamate / Motomachi) heritage",   application: "Andesite plinth coursing reinterpreting Western-quarter brickwork" },
      { name: "Chinatown red lacquer",         origin: "Yokohama Chukagai, Asia's largest Chinatown",     application: "Interior accent: ceremony-bench lacquer, ema board mounts" },
      { name: "Minato Mirai grid",             origin: "MM21 redevelopment masterplan, 1988 onward",      application: "Floor-plate logic of the building, with green-finger atria mirroring MM21's pedestrian routes" }
    ],
    buildingTypology: "Stacked CLT timber pavilions on a base-isolated steel frame, with tinted-glass magenta-rose curtain wall, copper roof shells, and an andesite plinth that ties the building to Hakone volcanic geology",
    referenceArchitects: ["SANAA (Kazuyo Sejima and Ryue Nishizawa)", "Sou Fujimoto", "Tadao Ando", "Foreign Office Architects (Yokohama Port Terminal lineage)"],
    silhouette: "A heart of stacked timber pavilions, anchored on a copper-roofed entry pavilion at the bay, doubling in the water at evening"
  },
  seismic: {
    code: "Building Standard Law of Japan (建築基準法), MLIT 2025 amendment, plus AIJ recommendations for seismic isolation in coastal Kanto",
    designSpec: "Yokohama is closer to the Sagami Trough than Tokyo. Subduction-zone risk is high; M7+ event probability is around 70% in 30 years for the wider Kanto region. MM21 sits on reclaimed land with non-trivial soil amplification. Hazard factor (Z) elevated relative to the city centre.",
    peakAccel: "0.6g design / 0.9g MCE",
    isolation: "Lead-rubber bearings at the steel base frame, 60 cm displacement capacity. Fluid-viscous dampers at four corners. The visible isolation gap at the plinth is dramatised as a horizontal copper shadow line.",
    notes: "Yokohama and the Kanto plain share Tokyo's seismic context but with elevated soil amplification on the MM21 reclaimed land. The CLT timber stack above the isolated base reduces mass, lowering the seismic forces compared to a concrete tower of the same height. The Sagami Trough subduction interface drives the design.",
    designConsequences: "Base isolation is non-negotiable in this seismic zone. The copper shadow line at the plinth is the visible engineering. Above the isolators, the timber pavilions can carry the ceremony spaces with much lower seismic forces, freeing the architecture from concrete-tower mass."
  },
  sections: {
    hero: {
      label: "港町の心",
      title: "Yokohama,",
      titleAccent: "港町の心",
      lead: "Japan's gateway to the world since 1859, when the port opened to international trade. Around 3.77 million people. Chukagai (Asia's largest Chinatown) and Yamate (the Western quarter) sit a short walk from each other. Minato Mirai 21 is the country's most ambitious modern waterfront. Andorra writes love in stone. Yokohama writes love in arrivals and departures.",
      viral: "A city built on people choosing to come, and choosing to stay",
      stats: [
        { n: "12m",      l: "Minatokokoro (the shared heart, +hologram)" },
        { n: "10",       l: "Heart-shaped Cor landmarks" },
        { n: "600",      l: "Kokoro no Ie by 2035" },
        { n: "1 hr/wk",  l: "Yokohama Hour on Cor FM" },
        { n: "Q1 2028",  l: "First Families Move In" }
      ]
    },
    monumentSection: {
      label: "港心",
      title: "Minatokokoro",
      lead: "The Port Heart. 12 metres of cross-laminated timber under a salt-proof titanium skin, the same heart every Cor city builds, sited on Minato Mirai 21 Pier 8 with sister piers reaching into the bay. Tiny against the MM21 skyline by design; the grandeur is the night-time heart of light blooming over the water and beating in sync with all six cities, weightless and switched off by day. Magenta-rose tinted glass, patinated copper, andesite plinth tied to Hakone volcanic geology.",
      viral: "Not the tallest tower in MM21. The most lived-in."
    },
    passivhaus: {
      label: "心の家",
      title: "Kokoro no Ie",
      subtitle: "Bay-courtyard family homes for the Kanto seaboard",
      lead: "Yokohama's binding constraint is not housing but aging (TFR around 1.20). The Yokohama Municipal Housing Corporation already builds 5,000 to 7,000 public units a year. The Cor del Món contribution is small and specific: 600 Kokoro no Ie family homes by 2035 as a CLT-bay-courtyard typology demonstrator, sited 250 in Kanagawa-ku (modular CLT prefab on city-owned brownfield), 200 in Tsurumi-ku (former industrial waterfront conversion), and 150 in Konan-ku southern hills. The contribution is the typology and the family-priority allocation, not the count.",
      viral: "A house that breathes with the bay wind off Yokohama Port",
      cards: [
        { icon: "leaf",   title: "Passive cooling, bay-cross ventilation", desc: "Deep timber eaves shade the south facade through the long Kanto summer. Cross-ventilation through a heart-shaped courtyard catches the bay wind. Building-scale energy use roughly 65% below a conventional Yokohama mid-rise." },
        { icon: "heart",  title: "Bay-courtyard timber blocks",            desc: "Each block of 12 units arranged around a heart-shaped courtyard with a small reedbed pond and a single zelkova tree. Communal under-eaves kitchen, shared bath house, rooftop drying court with bay view." },
        { icon: "hearth", title: "Family-first, three-generation",         desc: "Every unit: 3+ bedrooms, soundproofed nurseries, an alcove for an elder family member, sliding fusuma panels reconfiguring the floor plan as the family grows." },
        { icon: "key",    title: "Kanagawa family-priority overlay",       desc: "Allocation overlay through Yokohama Municipal Housing Corporation (Yokohama Shi Jutaku Kyokyu Kosha) family-housing scheme. Up to 25% purchase subsidy for under-35 Yokohama residents with two-plus years of local residency, scaled by number of children. Sits inside Kanagawa Prefecture's existing income-banded family-housing framework rather than parallel to it." },
        { icon: "sun",    title: "Net-zero, sea-breeze cooled",            desc: "Solar shingles, geothermal heat exchanger from the Hakone fault aquifer, rainwater harvesting into the courtyard reedbed, evaporative comfort through the eight humid weeks. Bills minimal year round." },
        { icon: "arc",    title: "Timeline: Q1 2028 start",                desc: "Phase 1 (2028-2030): 250 units in Kanagawa-ku (modular CLT prefab on city-owned brownfield). Phase 2 (2030-2033): 200 in Tsurumi-ku (former industrial waterfront conversion). Phase 3 (2033-2035): 150 in Konan-ku southern hills. Total 600. All builds reviewed by AIJ for the Sagami Trough seismic zone." }
      ],
      stats: [
        { n: "600",   l: "Homes by 2035" },
        { n: "65%",   l: "Energy below baseline" },
        { n: "Up to 25%", l: "Family Subsidy" },
        { n: "3+",    l: "Bedrooms Min" }
      ]
    },
    architecture: {
      label: "愛の建築",
      title: "Buildings That Greet the Sea",
      lead: "Heart-shaped buildings in CLT timber and titanium. Existing concrete walls along Bashamichi and Isezaki wrapped in seasonal lantern lattice, lit at dusk to mirror the bay-front promenade lanterns the city has loved since 1860.",
      viral: "Other cities have a skyline. Yokohama has a horizon line, doubled in the water.",
      murals: [
        { text: "おかえり",  sub: "Welcome home. Lantern lattice on a south-facing wall in Kanagawa-ku, deep rose against a titanium ground.",      gradient: "linear-gradient(135deg,#d63384,#7a1c4d)" },
        { text: "また来て",  sub: "Come again. Hands woven in copper mesh between two buildings on Bashamichi, illuminated at dusk.",                gradient: "linear-gradient(135deg,#e91e63,#d63384)" },
        { text: "港でね",    sub: "I'll meet you at the port. One phrase in shodo calligraphy across an apartment block in Sakuragicho.",            gradient: "linear-gradient(135deg,#f8b6cf,#e91e63)" }
      ]
    },
    media: {
      label: "横浜の声",
      title: "Yokohama Hour on the network broadcast",
      lead: "Yokohama does not build a station to compete with the ones it loves. The network broadcast is anchored in Andorra (Cor FM, Cor Play); Yokohama contributes the Yokohama Hour, a weekly Japanese-language strand recorded inside Minatokokoro and carried worldwide via Cor Play from 2036. Locally it works through the broadcasters that already speak for Kanagawa: a kindness segment for children co-produced with tvk and FM Yokohama under prefectural sponsorship, with NHK Yokohama's regional desk, the way community programming here is already made. FM Yokohama, NHK Yokohama, and tvk keep their place; Yokohama Hour is a gift into the network, never a station over them.",
      viral: "We did not need another radio station. We needed an hour the city would lend us.",
      outlets: [
        { icon: "mic", title: "Yokohama Hour · with FM Yokohama", desc: "A weekly Japanese-language hour recorded inside Minatokokoro and carried worldwide on Cor Play, produced with FM Yokohama, the bay's own station. City pop, harbour jazz, listener letters. A gift into the network, never a station over the city.", tags: ["Weekly", "Japanese first", "With FM Yokohama"] },
        { icon: "screen", title: "Kindness segment · with tvk + NHK Yokohama", desc: "A children's kindness strand co-produced with tvk and the NHK Yokohama regional desk under prefectural sponsorship, the way Kanagawa's community programming is already made. Animated harbour stories about welcoming the newcomer.", tags: ["With tvk", "Regional", "Children"], tagVariant: "soft" }
      ],
      soundtrackTitle: "横浜の音 · The Sound of Yokohama",
      soundtrackIntro: "The bay at dusk, in five songs: the postwar harbour ballad that named the city's blue lights, the city-pop that made Yokohama the genre's home, a seaside afternoon, and the young voice carrying it forward. Click any track to open a YouTube search.",
      soundtrack: [
        { track: "ブルー・ライト・ヨコハマ (Blue Light Yokohama)", artist: "Ayumi Ishida", released: 1968, note: "The Yokohama love song. A woman walking the harbour at night, the blue lights of the port around her. The clearest, oldest declaration any Japanese city has made to itself. If the building has one anthem, it is this." },
        { track: "海を見ていた午後 (Umi o Miteita Gogo)", artist: "Yumi Matsutoya", released: 1974, note: "An afternoon watching the sea from the Dolphin cafe above the bay. Yuming at her most still and tender. Longing without drama, the feeling of a quiet coast." },
        { track: "Plastic Love",            artist: "Mariya Takeuchi",              released: 1984, note: "City pop's defining track, recorded with her husband Tatsuro Yamashita. Yokohama is city pop's spiritual home; this is the song the whole world found again decades later and fell for." },
        { track: "Last Summer Whisper",     artist: "Anri",                          released: 1982, note: "A sun-bleached city-pop ballad in Japanese and English. The port at the end of August, when the humidity finally breaks and someone is leaving." },
        { track: "Plastic Love (Friday Night Plans cover)", artist: "Friday Night Plans", released: 2020, note: "The new generation answering the classic. Friday Night Plans is the Tokyo-Yokohama corridor's quiet bedroom-pop voice, proof the city's sound is still being written." }
      ]
    },
    traditions: {
      label: "伝統の再解釈",
      title: "A Port City, Hotter Fire",
      lead: "Yokohama has been welcoming arrivals since 1859. The traditions around food, music, and festival here already carry the memory of meeting strangers and taking them in. We turn up the warmth a little, and frame these traditions for couples and families.",
      viral: "Every arrival in Yokohama is already a love story. We just gave it a calendar.",
      categories: [
        { monogram: "食", title: "Food (味の心)", items: [
          ["Chukagai Cor weeks",      "A two-week love-themed strand inside Yokohama Chukagai (Chinatown) each February. Heart-shaped jian bing, double-shared dim sum baskets, dragon-and-phoenix wedding banquet menu open to all couples."],
          ["Bayside kaiseki",         "A bay-facing kaiseki tradition at the MM21 waterfront ryotei. The seventh course is always a single bowl shared from one chopstick rest."],
          ["Yamate yokopan",          "Yokohama's existing Yamate Heights bakeries (the city's Western-quarter sweet-bread tradition since the 1860s) host a Cor Saturday each month: heart-pressed yokopan loaves, profits seeding the next year's Cor Residency intake."],
          ["Iekei paired-bowl",       "The Yokohama-born iekei ramen tradition gets a paired-bowl Saturday: two diners, half noodles each, one shared iron pot of broth."]
        ]},
        { monogram: "音", title: "Music (音の心)", items: [
          ["Yokohama Jazz Promenade Cor strand", "The existing Yokohama Jazz Promenade (every October since 1993) gains a love-jazz strand at the Red Brick Warehouse. One new commission per year for two hearts."],
          ["Minato Beat",             "A new piece composed each year for the Daily Ceremony at Minatokokoro. Premiered every Cor sunset hour, broadcast network-wide via Cor FM's Yokohama Hour."],
          ["Bashamichi spring concert", "A small May concert in Bashamichi's heritage tram-line corridor, when the spring wind off the bay is at its softest. Local Yokohama jazz acts, no headliners."]
        ]},
        { monogram: "祭", title: "Festivals (祭の心)", items: [
          ["Minato Mirai Hanabi paired tickets", "The existing Minato Mirai Hanabi (August fireworks night) keeps its public seating. A small paired-ticket allocation is reserved for local couples and Cor Residents."],
          ["Yokohama Festival Cor strand", "A two-week strand inside the existing Yokohama Festival each June, with parades that connect Chukagai, Yamate, and Sakuragicho via the bayfront promenade."],
          ["Pier 8 ceremony pier",    "Sister piers at the new Pier 8 (planned 2028) become the network's bayside ceremony venue. Couples can renew vows under the lantern lights with the bay reflecting the rose."]
        ]},
        { monogram: "儀", title: "Rituals (儀の心)", items: [
          ["Ceremonies at Minatokokoro", "Wedding and renewal ceremonies in the topmost Pier 8 pavilion, looking out at the bay and the night skyline of MM21. Subsidised for Yokohama residents, premium for international couples."],
          ["Cha-no-yu pair sitting",     "An adapted tea ceremony for couples at Sankeien Garden's Rinshunkaku tea house. Two bowls, one motion. Open to anyone who has registered for a sitting at the Sankeien front desk."],
          ["Kokoro Yado at Yamate Heights", "The Cor Residency intake: ten residents per year (two from each of the other five Wave-1 cities), housed in restored Yamate Heights Western-quarter cottages. Walking distance to the port and the Yamate Italian Hill quarter."],
          ["Senbazuru letters",          "An older Japanese folding tradition adapted: handwritten letters folded into senbazuru cranes (paper cranes), strung once a year and exhibited at the Yokohama Museum of Art's open-call wall during Yokohama Triennale season."]
        ]}
      ]
    },
    youth: {
      label: "若者戦略",
      title: "A port that already welcomes. Now make it easier to stay.",
      lead: "Yokohama is Japan's most porous city by design: open since 1859, the first place foreign banks, schools, and churches were allowed in the country. Modern Japan already has a Highly Skilled Professional visa, the J-Find/J-Skip pathways, and a generous Specified Skilled Worker programme. Yokohama does not need a new visa category; what young residents lack is housing they can afford and childcare they can find. The Cor del Món contribution is concrete and small: bay-courtyard family housing, a partnership with Yokohama City University, and a Cor Residency exchange that puts ten incoming residents per year into restored Yamate Heights cottages.",
      viral: "Yokohama opened the gates in 1859. The work in 2030 is not opening more gates. It is keeping the lights on for the people already inside.",
      cards: [
        { icon: "hearth",    tag: "Housing",      title: "Kokoro no Ie family priority",            desc: "600 bay-courtyard family homes by 2035 (see the Hearth section), sized as a typology demonstrator against the Yokohama Municipal Housing Corporation's existing 5,000-7,000/year output. Allocated with priority to families under 35 already resident in Yokohama for two-plus years. Income-tested through Kanagawa Prefectural housing programmes that already exist." },
        { icon: "residency", tag: "Cor Residency", title: "Kokoro Yado, Yamate Heights",            desc: "Yokohama's contribution to the network Cor Residency. Ten incoming residents per year housed in restored Yamate Heights Western-style cottages (the 1860s foreign-settlement quarter). Two from each of the other five Wave-1 cities. Twelve-month stay, MM21 studio access, language exchange with the local YOKE programme." },
        { icon: "book",      tag: "Education",    title: "YCU Bay Studio (architecture exchange)",  desc: "Yokohama City University and Keio Yokohama partner with Cor del Món on a single, focused MArch studio: mass-timber-on-isolated-base, bay-courtyard housing, brownfield-to-family-housing conversion. Twenty students per year, including five fully funded seats for the other five cities. Not a new faculty; one studio that runs every spring." },
        { icon: "doublehearts", tag: "Childcare", title: "Bay-courtyard nurseries (12 months+)",   desc: "Free public childcare at the ground floor of every Kokoro no Ie block from 12 months. Built into the family housing, not as a separate facility, so the walk from kitchen to nursery is one staircase. Coordinated with the Yokohama Childcare Bureau's existing capacity expansion plan." },
        { icon: "leaf",      tag: "Health",        title: "Postnatal support at three wards",       desc: "Yokohama Municipal University Hospital, Saiseikai Yokohama-shi Tobu, and Yokohama Rosai expand postnatal mental-health coverage for new parents and couples through Japan's existing national health insurance. Telehealth across Kanagawa for hill-district families with limited transport." },
        { icon: "transit",   tag: "Movement",      title: "Heart Sea Bus loop",                     desc: "Rose-liveried small sea-bus connecting Minatokokoro, Yamashita Park, the Red Brick Warehouse, and the Tsurumi housing district. Subsidised for residents through a small tourism levy on the Sakuragicho cruise terminal. Frequencies set so a Tsurumi parent can do a school pickup, monument visit, and grocery loop on one ticket." },
        { icon: "heart",     tag: "Animals",       title: "Guide-dog partners",                     desc: "Kanagawa is home to one of Japan's guide-dog training centres, and a guide dog is the plainest lesson in love a child can meet: years of patient work so one person can walk the city unafraid. Minatokokoro hosts puppy-walker family days, school visits, and a quiet retirement-fostering scheme, alongside the neighbourhood community-cat (chiiki-neko) care that already keeps the port's strays fed, fixed, and counted." }
      ],
      stats: [
        { n: "10",     l: "Kokoro Yado residents/yr (incoming)" },
        { n: "600",    l: "Family homes by 2035 (Kokoro no Ie)" },
        { n: "20",     l: "YCU Bay Studio Master of Architecture seats/yr" },
        { n: "3.77M",  l: "Resident population (2024)" }
      ]
    },
    network: {
      label: "心の網",
      title: "Six cities. One heartbeat.",
      lead: "Yokohama joins Cor del Món as the second wave-1 city after Andorra. Below are the five other cities the network is being built with through 2030.",
      viral: "Andorra writes love in stone. Yokohama writes love in arrivals. Together, the world has both."
    },
    roadmap: {
      label: "長い弧",
      title: "Four stages, on Yokohama's pace",
      lead: "Minatokokoro is Yokohama's contribution to Cor del Món. Yokohama joins Andorra and Adelaide in the wave-1 trio, opening its monument in 2035-2036 and reaching the Generation milestone in 2060-2061.",
      viral: "Yokohama alone is a port that taught Japan how to greet the world. Yokohama inside Cor del Món is the eastern face of a network of six cities greeting each other every UTC tick.",
      milestones: [
        {
          year:     2028,
          stage: "Charter",
          commitment: "Cor Charter signed with Yokohama City and Kanagawa Prefecture (which already runs sister-city partnerships with Vancouver, Lyon, Mumbai, Manila, Shanghai, Odessa, and Constanta). International architecture competition for Minatokokoro awarded. Site secured at Minato Mirai 21 Pier 8. Adelaide signs its own Cor Charter the same year, anchoring the wave-1 parallel build.",
          metrics: { charterSigned: true, competitionAwarded: true, siteSecured: "MM21 Pier 8" },
          networkContribution: "Yokohama becomes Cor del Món's gateway to East Asia, joining Andorra (live since 2027) as the second city to sign. Hosts the second Cor Biennale of the network in 2029, staged at the Red Brick Warehouse and the MM21 promenade.",
          status: "concept",
          lastVerified: "2026-Q3"
        },
        {
          year:     2030,
          stage: "Break Ground",
          commitment: "Construction begins on Minatokokoro and on the first 400 Kokoro no Ie units in Kanagawa-ku. The YCU Bay Studio MArch programme opens its first cohort (twenty seats including five from network cities). Yokohama's Charter+Design phase complete; the building enters its base-isolation foundation pour.",
          metrics: { homesUnderConstruction: 400, baseStudioCohort: 20, baseIsolationPour: true },
          networkContribution: "Yokohama publishes the first ten Yokohama-authored Cor Patterns (mass-timber-on-isolated-base, bay-courtyard housing block, brownfield-to-family-housing). Andorra Daily Ceremony broadcasts have been running for two years; Yokohama hosts the second annual network Pattern-Library exchange.",
          status: "concept",
          lastVerified: "2026-Q3"
        },
        {
          year:     2036,
          stage: "Operational",
          commitment: "Minatokokoro opens. The Daily Ceremony begins broadcasting at the city's declared Cor hour (18:00 JST) from the topmost Pier 8 pavilion. All 600 Kokoro no Ie units delivered across Kanagawa-ku (250), Tsurumi-ku brownfield conversions (200), and Konan-ku southern hills (150). The first Cor Generation residents move into the network units, including a returning-expat cohort from Yokohama's diaspora cities. Resident population sustained at around 3.8M.",
          metrics: { homes: 1000, monumentHeightM: 12, fertilityRate: 1.5, residentsIncoming: 10, dailyCeremonyActive: true },
          networkContribution: "Yokohama joins Andorra in the Daily Ceremony rotation (Adelaide also operational from 2035). The network's three operational cities now host 30 Cor Residents per year between them. Yokohama-authored patterns reach 30 contributions to the Cor Pattern Library.",
          status: "concept",
          lastVerified: "2026-Q3"
        },
        {
          year:     2061,
          stage: "Generation",
          commitment: "Minatokokoro celebrates twenty-five years operational. The first Cor Generation residents who arrived in 2036 (then in their 20s, now in their 50s) have raised families inside the Kokoro no Ie stock. A second-wave expansion adds 400 units across Tsurumi-ku and Konan-ku, bringing the Cor total to 1,000 (still a typology demonstrator, not a public-housing programme). The Minatokokoro Pattern-Library archive opens in a small ceremony-pavilion annex on Pier 8.",
          metrics: { networkAgeYears: 25, totalHomes: 1000, generationAdults: 700 },
          networkContribution: "Yokohama graduates into network elder status alongside Andorra (2057) and Adelaide (2060). Yokohama mentors Wave-2 East Asian candidate cities (likely Kobe, Fukuoka, Busan, Singapore). The Minatokokoro Anthology (Letters to Minatokokoro bound annually) becomes a recognised volume of contemporary Japanese love poetry, exhibited globally through Yokohama Museum of Art.",
          status: "concept",
          lastVerified: "2026-Q3"
        }
      ]
    }
  },
  feasibility: {
    title: "Honest constraints",
    intro: "What a 12m monument on Pier 8 of MM21 actually has to negotiate with.",
    category: "Cultural facility on a Minato Mirai 21 reclaimed-land parcel with an associated public-housing scheme. Standard Yokohama City urban-development category, fitting inside the existing MM21 District master plan. No new permission package required.",
    permissionChain: [
      "Yokohama City Hall, Building Bureau (建築局, Kenchiku-kyoku), issues the kenchiku kakunin (建築確認, building confirmation). Yokohama Cultural and Tourism Bureau (文化観光局, Bunka-kanko-kyoku) prepares the cultural-anchor agreement; the Mayor of Yokohama signs.",
      "Minatomirai 21 Suishin Kyogi-kai (MM21 Promotion Council; the multi-stakeholder body of Yokohama City, Yokohama Minatomirai 21 Co., and major MM21 land-holders) reviews siting and integration with the master plan.",
      "Yokohama City Port and Harbor Bureau (港湾局, Kowan-kyoku), as the Pier 8 / Shinko-futo land-holder, signs the Pier 8 long-term cultural-anchor leasehold. Mitsubishi Estate is a major MM21 land-holder elsewhere (Landmark Tower district) but not the Pier 8 lessor.",
      "Kanagawa Prefecture, Land and Infrastructure Bureau (県土整備局), Housing Division approves the family-priority overlay on the Yokohama Municipal Housing Corporation scheme.",
      "Building Performance Evaluation Organization (Sei-no Hyoka Kikan, certified under the Building Standard Law) conducts the statutory seismic-isolation peer review for the LRB-bearing system. The Architectural Institute of Japan (AIJ) provides expert input but is a learned society, not a regulatory body.",
      "The architect-of-record (jugyo-shi-jimusho) registered with Kanagawa Prefecture handles the foreign-led design submission.",
      "Foreign Exchange and Foreign Trade Act (FEFTA) prior-notification or post-notification, administered by the Ministry of Finance plus the Agency for Cultural Affairs as the relevant ministry of jurisdiction, for foreign-source funding above the threshold."
    ],
    budgetSources: [
      "Yokohama City Cultural Promotion Bureau (Yokohama-shi Bunka Kanko Kyoku) annual cultural-infrastructure line.",
      "Kanagawa Prefecture Family Housing Subsidy (existing programme; Cor adds a family-priority overlay).",
      "Mitsubishi Estate development cooperation (in-kind site lease).",
      "Cor del Món network partner-share contribution.",
      "Japanese cultural foundations (Asahi Group Foundation, Toyota Foundation cultural arm, Mori Memorial Foundation).",
      "Agency for Cultural Affairs (Bunka-cho) cultural-infrastructure capital line for international cultural partnerships."
    ],
    items: [
      { area: "Land",                  detail: "MM21 Pier 8 is a leasehold negotiation with Yokohama City and Mitsubishi Estate (the major MM21 leaseholder). Not a freehold purchase. The MM21 supertall-ready zoning permits far more than 12m without special legislation, so height is a non-issue; the lease term and commercial structure take 24 to 36 months to settle from Charter year. The night-time heart of light is an evening projection under standard event-lighting permits." },
      { area: "Building permits",      detail: "Standard Japanese architecture-approval cycle is 24 to 36 months. Foreign-led design works through a Japanese architect-of-record (jugyo-shi). AIJ (Architectural Institute of Japan) review of base-isolation design (LRB bearings, fluid-viscous dampers) is rigorous; Sagami Trough subduction context is unforgiving on shortcuts." },
      { area: "Residency",             detail: "Kokoro Yado (Cor Residency intake at 15 per year) uses Japan's existing Highly Skilled Professional and Cultural Activities visa categories. No new visa proposed. Yamate Heights cottage stock supports the higher capacity than other network cities." },
      { area: "Funding compliance",    detail: "Project finance through a Japanese cultural-foundation framework (Public Interest Incorporated Foundation, koueki zaidan houjin). Yokohama City participation through existing sister-city budget allocations. No foreign-state funding; all sources disclosed under Japanese anti-money-laundering rules." },
      { area: "Cultural sensitivity",  detail: "Cor del Món branding overlaying Japanese venues is a real sensitivity. The project commits to Japanese language primacy on the Yokohama site, Japanese cultural-advisor leadership, and explicit non-imposition: Yokohama Hour (broadcast contribution) is into the network, not over Japanese broadcasters." },
      { area: "Compliance",            detail: "Building Standard Law of Japan (建築基準法), MLIT 2025 amendment, plus Yokohama Bayfront District design guidelines. A 12m heart sits far below everything in the MM21 context (Landmark Tower 296m, Cosmo Clock 21 ferris wheel 112m, routine 200m+ towers); the night-time heart of light is projection, not structure, angled and timed to respect the bayfront design guidelines." }
    ]
  },
  costs: {
    title: "Approximate costs (2026 USD)",
    monumentTotal: "USD 6 to 13 million",
    intro: "Order-of-magnitude estimates anchored against comparable Japanese cultural buildings (Mode Gakuen Cocoon Tower at 204m cost roughly USD 300M in 2008 yen). At 75m the Minatokokoro is a fraction of that, and the lighter mass-timber structure on isolators costs far less than a concrete tower. Real budgets after the international design competition and AIJ review.",
    stages: [
      { phase: "Charter (2028)",        range: "USD 0.5 to 1M",   scope: "International design competition + Japanese architect-of-record agreement + MM21 lease negotiation + Pier 8 site studies" },
      { phase: "Break Ground (2030-31)", range: "USD 1 to 2.5M",  scope: "Base-isolated steel frame foundation, LRB bearing installation, andesite plinth, sister-pier marine works" },
      { phase: "Construction (2031-35)", range: "USD 3 to 6.5M", scope: "CLT timber pavilion stack, titanium rainscreen skin, magenta-rose tinted glass, patinated copper roof shells, interior fitout" },
      { phase: "Operational (2036)",     range: "USD 1.5 to 3M",   scope: "Yokohama Hour broadcast studio, ceremony fitout, opening programme, Yokohama Triennale partnership integration" }
    ],
    fundingNote: "Project-finance structure: a Japanese cultural-foundation framework as the receiving entity. Funding for the monument leans private: Cor del Món network partner share (35-50%), Japanese corporate and family-foundation cultural arms (30-45%), Mitsubishi Estate land in-kind (10-20%), with Yokohama City and Kanagawa Prefecture only a modest enabling share (5-15%). The real public investment is the Kokoro no Ie family homes through the Yokohama Municipal Housing Corporation, not the landmark. Single-sovereign foreign funding excluded."
  },
  impact: {
    title: "Impact and benefit",
    items: [
      { metric: "600 CLT bay-courtyard family homes by 2035", note: "Sized as a typology demonstrator (about 1-2% of Yokohama Municipal Housing Corporation's annual 5,000-7,000 unit output). The novelty is the typology and the family-priority allocation. Demonstration value for other dense Japanese cities." },
      { metric: "15 Cor Residency intake per year",          note: "International port heritage: Yokohama opened in 1859. Yamate Heights Western-quarter cottages have higher capacity than other network cities. 15 per year is the highest intake in the network." },
      { metric: "Yokohama Hour on the network broadcast",     note: "Weekly Japanese-language slot from Minatokokoro studio inside the Andorra-anchored Cor FM. Adds Japanese voice to the network without displacing FM Yokohama or NHK Yokohama." },
      { metric: "12m heart + night heart of light",            note: "The same 12m heart every Cor city builds; the bay presence is a reversible heart of light at night, beating with the network, not structure. Tiny, cheap, salt-durable in titanium, doubled in the water at evening." },
      { metric: "Returning-expat anchor",                    note: "Japan's net immigration is small; the bigger demographic lever is returning expats. Kokoro no Ie family-priority allocation creates a concrete reason for Japanese-diaspora families abroad to come home to Yokohama." }
    ]
  },
  alternatives: {
    title: "Lighter expressions of the same idea",
    intro: "The proposal is offered as a creative-research design idea, not as a fundraising plan or a built commitment. The lightest expression below is the recommended default for any city that wishes to honour the idea without a built monument.",
    items: [
      { fallback: "Hologram-only expression (the recommended default)", reason: "The full Cor del Mon city experience delivered as projection, hologram, and augmented-reality installation hosted inside an existing public building, the same night-time heart of light without the 12 metre building beneath it. No new construction, no land take, no seismic or heritage risk, no permits beyond standard public-event approvals. Roughly one to three percent of the built-version cost. Six to eighteen months from agreement to opening night. Fully reversible. The local government keeps complete flexibility to time the installation to its own civic and cultural calendar and to relocate or remove it at any time. The safest and fastest path for any city that wishes to participate without committing to a permanent build." },
      { fallback: "Print, broadcast, and online expression", reason: "The design idea published as a book, an exhibition catalogue, a documentary, an open-access website, and a network of public talks, with no physical installation in the city. Lower cost again, no local-government commitment of any kind required." }
    ]
  }
};

export default vocab;
if (typeof window !== "undefined") {
  window.YokohamaVocab = vocab;
}
